Adds grip edge/vertex generation functionality from FHIR files.
bmeg/iceberg-schema-tools pull request #24
Opened 2023-10-31 19:36 UTC by matthewpeterkort

test: python -m pytest tests/integration/simplified/test_simplify_task.py::test_simplify_task -s  

There are some places where the edge labels look wrong. Guessing this edge generation might need to be done
with some knowledge of the schema to get the label names right on the edges.

also 

`iceberg data simplify tests/fixtures/simplify/synthea grip_data  --schema_path https://aced-public.s3.us-west-2.amazonaws.com/aced-test.json --dialect GRIP`

for testing with more data
Getting some validation errors on some of the data, not sure if using the right schema or not.

2023-11-03 18:28 UTC, bwalsh requested changes
Looks good.  One minor comment below re. debugging statements.
See issue, please write up a use case that describes what this is and when / why to use it.

2023-11-03 18:28 UTC, bwalsh commented on iceberg_tools/data/simplifier/__init__.py
> +    print("SIMPLIFIED ORIG: ", simplified)
We should remove debugging statement.

2023-11-03 18:28 UTC, bwalsh commented on iceberg_tools/data/simplifier/__init__.py
> +    print("SIMPLIFIED: ", simplified)
same ...

2023-11-03 18:28 UTC, bwalsh commented on iceberg_tools/schema/fhir_resources/binding_lookup.py
> +        connection.execute('DROP table IF EXISTS element_bindings')
Good catch, thanks

2024-08-26 18:09 UTC, matthewpeterkort commented
This got implemented in https://github.com/bmeg/jsonschemagraph instead

2024-08-26 18:09 UTC, closed without merging